### Add notes
POST http://localhost:5000/notes

{
    "title": "My note",
    "tags":[ "tag1", "tag2" ],
    "body": "this is example of note"
}

### Get All Notes
GET http://localhost:5000/notes

### Get Note by ID
GET http://localhost:5000/notes/aRSXLscagiYRRw5m

### Update Note
PUT http://localhost:5000/notes/aRSXLscagiYRRw5m

{
    "title": "Remember me to do swimming class",
    "tags":[ "sport", "water" ],
    "body": "please remember me to do swimming class, this is importan for my final exam"
}

### Delete Note
DELETE http://localhost:5000/notes/QLUIiIIRBPxXlGbt